### ISSUE TITLE
Wrong measures for Wind

### ISSUE THREAD

**Issue by Giapass** [jabiologo/rWind#16]
Hi,
Your package is really helpfull to download and process wind data. I just have a problem with the data gathered
using wind.dl_2. The speed and direction for the winds between 2012-03-23 12:00:00 UTC and 2012-03-24 09:00:00 UTC are non sense. I checked the web page of NOAA and there is not warning against this values >300 for speed. Have you already noted something similar? In case the data are wrong from source how can you exclude or convert to NAs the wrong values
I attached here my script for more details:
dt <- seq(ymd_hms(paste(2012,3,20,06,00,00, sep="-")),  
          ymd_hms(paste(2012,03,24,09,00,00, sep="-")),by="3 hours")#time
wind_series <- wind.dl_2(dt,-84,-70,-21,-3)  #wind.dl_2 to download the time series
wind_series_layer <- wind2raster(wind_series)  #wind2raster function adapted to work with this lists of wind

**Comment by jabiologo** [comment]
Hi Giapass,

 You are absolutely right, I'd never seen something similar. You can check manually that the error comes from the source here:
https://pae-paha.pacioos.hawaii.edu/erddap/griddap/ncep_global.graph?ugrd10m%5B(2012-03-24T00:00:00Z)%5D%5B(-84.0):(-70.0)%5D%5B(339):(357)%5D,vgrd10m%5B(2012-03-24T00:00:00Z)%5D%5B(-84.0):(-70.0)%5D%5B(339):(357)%5D&.draw=vectors&.vars=longitude%7Clatitude%7Cugrd10m%7Cvgrd10m&.color=0x000000&.bgColor=0xffccccff

As you can see, the error comes from the U wind component, which is set to >200 for the whole area... I really don't know what's happen there... I'll try to figure it out.
I think the best idea would be to remove the whole data set if you find values > 200 for the U component...

**Comment by Giapass** [comment]
Thanks so much. 
True, if it comes from source only exclusion of the values can work.
